/**
 * Grid List
 */
 const gridData = [
  {
    image: "assets/img/city-guide/catalog/01.jpg",
    title: 'Berlin Business Hotel',
    rating: "5.0",
    people_count: "48",
    price: '200',
    location: "1.4",
    city:"Berlin",
    district:"Berlin-Mitte",
    category:"Accomodation",
    property:"Hotel",
    rooms: "1-room",
    amenities:"parking",
    facilities:"kitchen"
  },
  {
    image: "assets/img/city-guide/catalog/02.jpg",
    title: 'Big Tree Cottage',
    rating: "4.8",
    people_count: "24",
    price: '500',
    location: "0.5",
    city:"Hamburg",
    district:"Charlottenburg",
    category:"Food & Drink",
    property:"Cottage",
    rooms: "2-rooms",
    amenities:"restaurant",
    facilities:"private-bathroom"
  },
  {
    image: "assets/img/city-guide/catalog/03.jpg",
    title: 'Grand Resort & Spa',
    rating: "4.9",
    people_count: "43",
    price: '800',
    location: "1.8",
    city:"Munich",
    district:"Prenzlauer Berg",
    category:"Shopping",
    property:"Land",
    rooms: "3-rooms",
    amenities:"pet-friendly",
    facilities:"air-conditioning"
  },
  {
    image: "assets/img/city-guide/catalog/04.jpg",
    title: 'Serene Stays',
    rating: "5.0",
    people_count: "12",
    price: '1,000',
    location: "3.2",
    city:"Koln",
    district:"Friedrichshain",
    category:"Art & History",
    property:"Boutique Hotel",
    rooms: "4-rooms",
    amenities:"room-service",
    facilities:"desk"
  },
  {
    image: "assets/img/city-guide/catalog/05.jpg",
    title: 'Leisure Inn',
    rating: "4.0",
    people_count: "9",
    price: '200',
    location: "2.1",
    city:"Frankfurt am Main",
    district:"Kreuzberg",
    category:"Entertainment",
    property:"Commercial",
    rooms: "5-rooms",
    amenities:"fitness-center",
    facilities:"kitchen"
  },
  {
    image: "assets/img/city-guide/catalog/06.jpg",
    title: 'Bliss Apartment',
    rating: "4.8",
    people_count: "32",
    price: '300',
    location: "1.9",
    city:"Berlin",
    district:"Berlin-Mitte",
    category:"Medicine",
    property:"Apartment",
    rooms: "1-room",
    amenities:"free-wifi",
    facilities:"kitchen"
  },
  {
    image: "assets/img/city-guide/catalog/07.jpg",
    title: 'Merry Berry Motel',
    rating: "4.5",
    people_count: "13",
    price: '900',
    location: "0.4",
    city:"Hamburg",
    district:"Charlottenburg",
    category:"Beauty",
    property:"Motel",
    rooms: "2-rooms",
    amenities:"spa-lounge",
    facilities:"terrace"
  },
  {
    image: "assets/img/city-guide/catalog/08.jpg",
    title: 'Serenity Hotel',
    rating: "5.0",
    people_count: "17",
    price: '1,000',
    location: "1.6",
    city:"Munich",
    district:"Prenzlauer Berg",
    category:"Auto Service",
    property:"Hotel",
    rooms: "3-rooms",
    amenities:"swimming-pool",
    facilities:"terrace"
  },
  {
    image: "assets/img/city-guide/catalog/09.jpg",
    title: 'Repose Hotel',
    rating: "5.0",
    people_count: "45",
    price: '700',
    location: "1.4",
    city:"Koln",
    district:"Friedrichshain",
    category:"Accomodation",
    property:"Hotel",
    rooms: "4-rooms",
    amenities:"parking",
    facilities:"washing-machine"
  },
  {
    image: "assets/img/city-guide/catalog/10.jpg",
    title: 'Tranquil Hostel',
    rating: "4.0",
    people_count: "15",
    price: '100',
    location: "1.7",
    city:"Frankfurt am Main",
    district:"Kreuzberg",
    category:"Food & Drink",
    property:"Hostel",
    rooms: "5-rooms",
    amenities:"parking",
    facilities:"heating"
  },
  {
    image: "assets/img/city-guide/catalog/11.jpg",
    title: 'Soothe & Stay',
    rating: "4.6",
    people_count: "10",
    price: '350',
    location: "2.4",
    city:"Berlin",
    district:"Berlin-Mitte",
    category:"Shopping",
    property:"Boutique Hotel",
    rooms: "1-room",
    amenities:"parking",
    facilities:"laundry-service"
  },
  {
    image: "assets/img/city-guide/catalog/12.jpg",
    title: 'Best Nest Apartment',
    rating: "1.9",
    people_count: "10",
    price: '550',
    location: "1.1",
    city:"Hamburg",
    district:"Charlottenburg",
    category:"Art & History",
    property:"Apartment",
    rooms: "2-rooms",
    amenities:"restaurant",
    facilities:"kitchen"
  },
  {
    image: "assets/img/city-guide/catalog/13.jpg",
    title: 'Pine Cottage',
    rating: "5.0",
    people_count: "12",
    price: '630',
    location: "4.7",
    city:"Munich",
    district:"Prenzlauer Berg",
    category:"Entertainment",
    property:"Cottage",
    rooms: "2-rooms",
    amenities:"room-service",
    facilities:"kitchen"
  },
  {
    image: "assets/img/city-guide/catalog/14.jpg",
    title: 'Greenpoint Boutique Hotel',
    rating: "4.9",
    people_count: "12",
    price: '400',
    location: "0.4",
    city:"Koln",
    district:"Friedrichshain",
    category:"Medicine",
    property:"Hotel",
    rooms: "3-rooms",
    amenities:"parking",
    facilities:"air-conditioning"
  },
  {
    image: "assets/img/city-guide/catalog/15.jpg",
    title: 'Crystal Apartment',
    rating: "4.9",
    people_count: "52",
    price: '260',
    location: "1.5",
    city:"Berlin",
    district:"Kreuzberg",
    category:"Beauty",
    property:"Apartment",
    rooms: "2-rooms",
    amenities:"bar",
    facilities:"heating"
  },
];

export { gridData };
